# Generated by Django 5.0.1 on 2025-11-16 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        # Add created_at and updated_at to Assessment (nullable first, then populate, then make non-null)
        migrations.AddField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        # Add created_at and updated_at to KnowledgeGap
        migrations.AddField(
            model_name='knowledgegap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgegap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        # LearningPath already has created_at and updated_at, just add db_index
        migrations.AlterField(
            model_name='learningpath',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        # Data migration: populate created_at from existing timestamp fields
        migrations.RunSQL(
            sql="UPDATE assessments SET created_at = completed_at WHERE created_at IS NULL;",
            reverse_sql="UPDATE assessments SET created_at = NULL;",
        ),
        migrations.RunSQL(
            sql="UPDATE knowledge_gaps SET created_at = identified_at WHERE created_at IS NULL;",
            reverse_sql="UPDATE knowledge_gaps SET created_at = NULL;",
        ),
        # Make fields non-nullable
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='knowledgegap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='knowledgegap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['student', '-completed_at'], name='assessments_student_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['subject', '-completed_at'], name='assessments_subject_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['score'], name='assessments_score_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgegap',
            index=models.Index(fields=['student', 'resolved'], name='knowledge_gaps_student_resolved_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgegap',
            index=models.Index(fields=['subject', 'resolved', '-severity'], name='knowledge_gaps_subject_resolved_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['student', 'completed'], name='learning_paths_student_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['subject', 'completed'], name='learning_paths_subject_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpathitem',
            index=models.Index(fields=['learning_path', 'order'], name='learning_path_items_path_order_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpathitem',
            index=models.Index(fields=['learning_path', 'completed'], name='learning_path_items_path_completed_idx'),
        ),
    ]
