# Generated by Django 5.0.1 on 2025-11-16 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentmetadata',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_metadata', to='content.educationalcontent'),
        ),
        migrations.AddField(
            model_name='filesearchstore',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='file_search_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='content.filesearchstore'),
        ),
        migrations.AlterUniqueTogether(
            name='contentmetadata',
            unique_together={('content', 'key')},
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['subject', 'difficulty'], name='educational_subject_a9c528_idx'),
        ),
    ]
