# Generated by Django 5.0.1 on 2025-11-16 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmetadata',
            name='key',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='author',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='indexed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='publication_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='title',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='filesearchstore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='filesearchstore',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='filesearchstore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='contentmetadata',
            index=models.Index(fields=['content', 'key'], name='content_met_content_42c3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='educational_uploade_463f65_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['indexed', '-created_at'], name='educational_indexed_748c93_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['subject', 'difficulty', 'indexed'], name='educational_subject_b61866_idx'),
        ),
        migrations.AddIndex(
            model_name='filesearchstore',
            index=models.Index(fields=['created_by', '-created_at'], name='file_search_created_248b77_idx'),
        ),
    ]
